### ISSUE TITLE
Warning: Failed prop type: Invalid prop `styles` supplied to `TransitionMotion`.

### ISSUE THREAD

**Issue by geryit** [maisano/react-router-transition#58]
I started to see this after upgrading to v1. Is there a quick fix for this?

```js
Warning: Failed prop type: Invalid prop `styles` supplied to `TransitionMotion`.
```

```js
const slideLeft = {
    atEnter: {
      opacity: 0,
      offset: 100,
      pos: 0,
    },
    atLeave: {
      opacity: 0,
      offset: -100,
      pos: 2,
    },
    atActive: {
      opacity: 1,
      offset: 0,
      pos: 1,
    },
    mapStyles(styles) {
      return {
        position: (styles.pos <= 1) ? 'relative' : 'absolute',
        opacity: styles.opacity,
        transform: `translateX(${styles.offset}%)`,
      };
    },
  };
```

```js
<RouteTransition
pathname={params.location.pathname}
className="transition-wrapper"
{...slideLeft}
 >
<Switch key={params.location.key} location={params.location}>
  <Route path={`${match.url}/info/`} component={PatientInfoPage} />
  <Route path={`${match.url}/confirmed/`} component={ShowConfirmationPage} />
  </Switch>
</RouteTransition>
```

**Comment by maisano** [comment]
@geryit if you've updated to `1.0.0`, you should use the `AnimatedSwitch` component:

```jsx
<AnimatedSwitch
  className="transition-wrapper"
  {...slideLeft}
>
  <Route path={`${match.url}/info/`} component={PatientInfoPage} />
  <Route path={`${match.url}/confirmed/`} component={ShowConfirmationPage} />
</AnimatedSwitch>
```

**Comment by th0th** [comment]
I am using 1.0.0 and I am using `AnimatedSwitch` but I am still getting the error:

Warning: Failed prop type: Invalid prop `styles` supplied to `TransitionMotion`.

**Comment by hhg2288** [comment]
having the same error here. I saw that the propTypes are correct, I can define as a `wrapperComponent` a custom react element. Do you see a possible issue here?

```
import {AnimatedSwitch, spring} from 'react-router-transition';
import {Div} from 'glamorous';

function mapStyles(styles) {
  return {
    transform: `translateX(${styles.offset}%)`
  };
}

const pageTransitions = {
  atEnter: {
    offset: 100
  },
  atLeave: {
    offset: spring(-100, {
      stiffness: 70,
      damping: 27
    })
  },
  atActive: {
    offset: spring(0, {
      stiffness: 70,
      damping: 27
    })
  }
};

const App = () => (
<AnimatedSwitch {...pageTransitions} mapStyles={mapStyles} wrapperComponent={Div}>
        <Route exact path="/" component={Home} />
        <Route path="/step-1" component={NameStep} />
      </AnimatedSwitch>
);

export default App;
```

and yes, `Div` can receive `style` as a Prop

**Comment by maisano** [comment]
hm, which version of `react-motion` are you using? and what is the value of `styles` at the time of that warning being logged?

**Comment by hhg2288** [comment]
I updated to version `1.0.1` and the warning dissapear :)

**Comment by a-nozeret** [comment]
Still getting the error using AnimatedSwitch, with the latest version here.
```
react-router-transition@1.0.1
react-motion@0.5.1
react-router-dom@4.2.2
```

**Comment by a-nozeret** [comment]
https://github.com/chenglou/react-motion/issues/268#issuecomment-292324479
TransitionMotion expects styles.key to be a string.

Solve it quickly by using the props from withRouter and adding to AnimatedSwitch the location object + a key of type String.

E.g. `<AnimatedSwitch location={{ ...location, key: '' }} ...`

@maisano in AnimatedSwitch.js:35 you could ensure the default key is a String.

**Comment by ranfdev** [comment]
Fixed with the solution of @a-nozeret.
To solve i did:

```
<App>
   <AnimatedSwitch
     ...
     location={...this.props.location, key: ''}
</App>
```
and i wrapped the App component using `withRouter()`:

```withRouter(App)```

**Comment by jeromepeters** [comment]
I'm still facing this issue. 

```jsx
                    <AnimatedSwitch atEnter={{opacity: 0}} atLeave={{opacity: 0}} atActive={{opacity: 1}} className="switch-wrapper">
                        <Route exact path="/" component={Home}/>
                        <Route path="/contact" component={Contact}/>
                    </AnimatedSwitch>
```

I tried to export the component with ``withRouter()`` and ``location={{...this.props.location, key: ''}}``, which removes the error, but unfortunately the routes too. So I'm getting a blank page. 

Could someone give me a hint where my problem is? Here is a [gist](https://gist.github.com/b337c46c5171602f3c7e6cb361866894) without the ``withRouter()`` and ``location={{...this.props.location, key: ''`` part.

**Comment by maisano** [comment]
@jeromepeters are you using hash history?

**Comment by maisano** [comment]
just published `1.1.1`–this should be fixed there.

**Comment by jeromepeters** [comment]
@maisano no, I don't use the ``hash history``, but version ``1.1.1`` fixed it. Thank you!
